### PR TITLE
Error when deleting parent with dependent destroy when child uses destroyed_at

### LINKED ISSUE #53: Error when deleting parent with dependent destroy when child uses destroyed_at.
Hi guys, I made a new project and got a no method error.  I came across [#46](https://github.com/dockyard/ruby-destroyed_at/issues/46)
Am I using it with something that's incompatible?  It's been awhile since this project's been touched so thanks for looking at it.

[Here's the example app](https://github.com/daslicious/destroyed_at_example)
```ruby 
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
end

class Comment < ActiveRecord::Base
  include DestroyedAt
  belongs_to :post
end
```

```ruby
a = Post.create
b = a.comments.create
a.destroy

NoMethodError: undefined method `destroyed_at' for #<Post:0x007f946c5df360>
```

```ruby
source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.1'
# Use postgresql as the database for Active Record
gem 'pg'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'

  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end


gem 'destroyed_at'
```

### PR DESCRIPTION
**Pull request by minimul**
Fixes #53

### CODE REVIEW

**Comment by bcardarella** [comment]
@minimul can you remove the version bump and can you add a test case for this?

**Comment by minimul** [comment]
Done.

**Comment by bcardarella** [comment]
Squash/rebase please.

@michaeldupuisjr ^

**Comment by minimul** [comment]
Done.

**Comment by philipdesmedt** [comment]
Can we merge this and deploy a new release? Having the same issue...

**Comment by michaeldupuisjr** [comment]
Thanks @minimul! Will push a release shortly.

**Comment by philipdesmedt** [comment]
@michaeldupuisjr is it also possible to release this on rubygems.org?

**Pull request merged**
